name: Deploy site to GitHub Pages

on:
  push:
    branches: [main]  # change to your branch if not 'main'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: .  # assumes index.html is in root

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
